<a href="https://colab.research.google.com/github/TejasDharmale/Pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['a', 'b', 'c']
my_list = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10,'2':20,'c':30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index= labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series([my_list])

0    [10, 20, 30]
dtype: object

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

a    10
2    20
c    30
dtype: int64

# Creating DataFrame

In [8]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
pd.Series(data)

Name             [John, Anna, Peter, Linda]
Age                        [28, 34, 29, 42]
City      [New York, Paris, Berlin, London]
Salary         [65000, 70000, 62000, 85000]
dtype: object

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
col = ['Name','Age','City','Salary']
df2 = pd.DataFrame(data_list,columns= col)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [12]:
df2.iloc[[2]] #index location

    Name  Age    City  Salary
2  Peter   29  Berlin   62000

In [13]:
df2 ['Designation']= ['Doctor','Engg','Teacher','Enterperuar']

In [14]:
df2

    Name  Age      City  Salary  Designation
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000         Engg
2  Peter   29    Berlin   62000      Teacher
3  Linda   42    London   85000  Enterperuar

In [15]:
df2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2

    Name  Age      City  Salary  Designation
0   John   28  New York   65000       Doctor
1   Anna   34     Paris   70000         Engg
2  Peter   29    Berlin   62000      Teacher
3  Linda   42    London   85000  Enterperuar

In [17]:
df2.drop('Designation',axis=1,inplace=True)

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2.iloc[[1,3]]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [20]:
df2.loc[[1],['Name','Salary']]

   Name  Salary
1  Anna   70000

In [21]:
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [22]:
df2[(df2["Age"]>30)& (df2['City']=="Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

#Missing Data

In [23]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [25]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [26]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [27]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing missing data

In [28]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [29]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [30]:
from copy import replace
df.fillna(value=0,inplace=True)

In [31]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [32]:
df.mean()

A    2.4
B    3.0
C    1.2
D    1.2
dtype: float64

In [33]:
df.drop_duplicates()

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

#mergering Dataframe

In [34]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [35]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [36]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [37]:
pd.merge(employees,salaries,on="employee_id",how="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [38]:
pd.merge(employees,salaries,on="employee_id",how="outer")

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [39]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [40]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

#Group by methods

In [41]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

df = pd.DataFrame(data)

In [42]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [43]:
c = df.groupby("Category")["Sales"].sum()
c

Category
A    570
B    930
Name: Sales, dtype: int64

In [44]:
b = df.groupby('Store')["Sales"].sum()
b

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [45]:
g = df.groupby(['Category','Store'])['Sales'].sum()
g

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [46]:
df['Sales'].agg(['mean', 'median', 'min', 'max', 'count', 'std'])

mean      187.500000
median    190.000000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64

### Pivot Table

In [47]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

###In pandas, a pivot table is used to summarize and analyze data by grouping rows and calculating values such as the sum, average, count, minimum, or maximum.

In [48]:
pd.pivot_table(df,values="Sales",index="Region", columns="Product")

Product      A      B      C      D
Region
East     514.6    NaN    NaN    NaN
North      NaN    NaN  511.8    NaN
South      NaN    NaN    NaN  340.2
West       NaN  679.0    NaN    NaN

In [49]:
pd.crosstab(df["Region"],df["Product"])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

###In pandas, pd.crosstab() is used to calculate the frequency (count) of combinations between two or more categorical variables. It helps you understand how categories are distributed across groups.

###DataFrame Basic Operation

In [50]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [51]:
df1.shape

(5, 3)

In [52]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [54]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [55]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [56]:
df1["A"]+1

0    2
1    3
2    4
3    5
4    6
Name: A, dtype: int64

In [57]:
def square(x):
  return x**2

In [60]:
df1["B"] = df1["B"].apply(square)

In [61]:
df1

   A     B    C
0  1   100  100
1  2   400  200
2  3   900  300
3  4  1600  400
4  5  2500  500